//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vet_mgmt_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PatientsMedicalProcedures = new HashSet<PatientsMedicalProcedure>();
        }
    
        public int PatientID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int OwnerID { get; set; }
        public int AnimalID { get; set; }
        public int MedicalProcedureID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientsMedicalProcedure> PatientsMedicalProcedures { get; set; }
    }
}
