//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vet_mgmt_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VetMgmtSystemDbEntities : DbContext
    {
        public VetMgmtSystemDbEntities()
            : base("name=VetMgmtSystemDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<MedicalProcedure> MedicalProcedures { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientsMedicalProcedure> PatientsMedicalProcedures { get; set; }
        public virtual DbSet<PriceHistory> PriceHistories { get; set; }
        public virtual DbSet<ZipCity> ZipCities { get; set; }
        public virtual DbSet<TreatmentHistory> TreatmentHistories { get; set; }
    }
}
